events {
  worker_connections 1024;
}

http {
  resolver 127.0.0.11 valid=10s ipv6=off;

  server {
    listen 80;
    server_name sensitivedata.ca www.sensitivedata.ca localhost 127.0.0.1;

    location /api/auth/ {
      set $auth_service auth-service:3001;
      rewrite ^/api/auth/(.*)$ /auth/$1 break;
      proxy_pass http://$auth_service;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/chat/ {
      client_max_body_size 25M;
      set $chat_service chat-service:3002;
      rewrite ^/api/chat/(.*)$ /chat/$1 break;
      proxy_pass http://$chat_service;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_buffering off;
      proxy_cache off;
      chunked_transfer_encoding on;
      proxy_read_timeout 600s;
    }

    location / {
      set $chat_ui chat-ui:3000;
      proxy_pass http://$chat_ui;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
