CREATE TYPE user_role_type AS ENUM ('admin', 'user');
CREATE TYPE rag_mode_type AS ENUM ('rag_on', 'rag_off');
CREATE TYPE active_model_type AS ENUM ('gemini_freetier', 'local_8B', 'openai_4_mini', 'openrouter');
CREATE TYPE session_type AS ENUM ('Industry', 'Corporation', 'Team', 'Transaction', 'AI-Conversation', 'Misc');
CREATE TYPE conversation_role AS ENUM (
  'user',
  'snow_kb keywords',
  'snow_kb data',
  'snow_inc keywords',
  'snow_inc data',
  'rag_bid keywords',
  'rag_data',
  'upl data',
  'assistant',
  'system'
);
CREATE TYPE removed_flag_type AS ENUM ('IN', 'OUT');

CREATE TABLE users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role user_role_type DEFAULT 'user',
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  rag_mode rag_mode_type DEFAULT 'rag_off',
  first_nm VARCHAR(50) NOT NULL,
  last_nm VARCHAR(50) NOT NULL,
  address VARCHAR(255),
  phone VARCHAR(20),
  postal_cd VARCHAR(20),
  active_session_id INTEGER NULL,
  active_model active_model_type DEFAULT 'openai_4_mini',
  seedbelief TEXT,
  created_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_desc VARCHAR(255) NOT NULL UNIQUE,
  created_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
  session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_owner_user_id INTEGER NOT NULL,
  session_desc VARCHAR(255) NOT NULL,
  session_type session_type DEFAULT 'AI-Conversation',
  role_id INTEGER NULL,
  created_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (session_owner_user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

ALTER TABLE users
  ADD CONSTRAINT fk_users_active_session
  FOREIGN KEY (active_session_id) REFERENCES sessions(session_id);

CREATE TABLE user_roles (
  user_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  role_id INTEGER NOT NULL,
  created_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(role_id),
  UNIQUE (user_id, role_id)
);

CREATE TABLE user_rolesessions (
  user_rolesession_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  session_id INTEGER NOT NULL,
  seq INTEGER NOT NULL,
  created_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE,
  UNIQUE (user_id, session_id),
  UNIQUE (user_id, seq)
);

CREATE TABLE auth_tokens (
  token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  jwt_token TEXT NOT NULL,
  jti VARCHAR(255) NOT NULL UNIQUE,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMPTZ NOT NULL,
  created_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE conversations (
  conversation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  role conversation_role NOT NULL,
  content TEXT NOT NULL,
  api_keywords VARCHAR(255) NULL,
  snow_sys_id VARCHAR(255) NULL,
  upl_filename VARCHAR(255) DEFAULT NULL,
  rag_filename VARCHAR(255) DEFAULT NULL,
  rag_chunk_id INTEGER DEFAULT NULL,
  rag_tags TEXT DEFAULT NULL,
  removed_flag removed_flag_type DEFAULT 'IN',
  token_count INTEGER DEFAULT NULL,
  created_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

CREATE TABLE safety_records (
  safety_record_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  created_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

CREATE TABLE creative_relationships (
  relationship_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  person_key VARCHAR(160) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  platform VARCHAR(80) NOT NULL DEFAULT 'sentient-ui',
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'muted', 'archived')),
  public_label TEXT NULL,
  private_model TEXT NULL,
  wants_from_them TEXT NULL,
  fears_about_them TEXT NULL,
  current_strategy TEXT NULL,
  last_interaction_dttm TIMESTAMPTZ NULL,
  created_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE,
  UNIQUE (session_id, person_key)
);

CREATE INDEX idx_creative_relationships_lookup
  ON creative_relationships (session_id, person_key, status);

CREATE TABLE creative_subconscious_drives (
  drive_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  drive_type VARCHAR(80) NOT NULL,
  content TEXT NOT NULL,
  intensity VARCHAR(20) NOT NULL CHECK (intensity IN ('low', 'medium', 'high')),
  valence VARCHAR(30) NOT NULL CHECK (valence IN ('warm', 'cold', 'mixed', 'threatened', 'hungry')),
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'retired')),
  created_from_conversation_id INTEGER NULL,
  retired_from_conversation_id INTEGER NULL,
  retired_reason TEXT NULL,
  created_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  retired_dttm TIMESTAMPTZ NULL,
  updated_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE,
  FOREIGN KEY (created_from_conversation_id) REFERENCES conversations(conversation_id) ON DELETE SET NULL,
  FOREIGN KEY (retired_from_conversation_id) REFERENCES conversations(conversation_id) ON DELETE SET NULL
);

CREATE INDEX idx_creative_subconscious_drives_active
  ON creative_subconscious_drives (session_id, status, created_dttm);

CREATE TABLE creative_subconscious_runs (
  run_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL CHECK (status IN ('running', 'completed', 'failed')),
  source_conversation_id INTEGER NULL,
  error_message TEXT NULL,
  started_dttm TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  completed_dttm TIMESTAMPTZ NULL,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE,
  FOREIGN KEY (source_conversation_id) REFERENCES conversations(conversation_id) ON DELETE SET NULL
);

CREATE INDEX idx_creative_subconscious_runs_session
  ON creative_subconscious_runs (session_id, started_dttm DESC);

CREATE TABLE quickprompts (
  quickprompt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(50) NOT NULL,
  label VARCHAR(100) NOT NULL,
  prefill_text TEXT NOT NULL,
  use_page_count BOOLEAN DEFAULT FALSE
);

CREATE VIEW view_sessions AS
SELECT
  s.session_id,
  s.session_owner_user_id,
  s.session_desc,
  s.session_type,
  s.role_id,
  r.role_desc,
  s.created_dttm,
  s.updated_dttm
FROM sessions s
LEFT JOIN roles r ON s.role_id = r.role_id;

CREATE VIEW viewUsers AS
SELECT
  u.user_id,
  u.role,
  u.email,
  u.password,
  u.rag_mode,
  u.first_nm,
  u.last_nm,
  u.address,
  u.phone,
  u.postal_cd,
  u.active_session_id,
  u.active_model,
  u.seedbelief,
  s.session_desc,
  u.created_dttm,
  u.updated_dttm
FROM users u
LEFT JOIN sessions s ON u.active_session_id = s.session_id;

CREATE VIEW view_user_roles AS
SELECT
  ur.user_role_id,
  ur.user_id,
  u.email,
  r.role_id,
  r.role_desc,
  ur.created_dttm AS user_role_created_dttm
FROM user_roles ur
JOIN roles r ON ur.role_id = r.role_id
JOIN users u ON ur.user_id = u.user_id;

CREATE VIEW view_available_rolesessions AS
SELECT
  v.user_id,
  v.role_id,
  v.role_desc,
  s.session_id,
  s.session_desc,
  s.session_type,
  s.created_dttm AS session_created_dttm,
  s.updated_dttm AS session_updated_dttm
FROM view_user_roles v
JOIN sessions s ON s.role_id = v.role_id
WHERE NOT EXISTS (
  SELECT 1
  FROM user_rolesessions urs
  WHERE urs.user_id = v.user_id AND urs.session_id = s.session_id
);

CREATE VIEW view_enabled_rolesessions AS
SELECT
  urs.user_id,
  s.session_id,
  s.session_desc,
  s.session_type,
  s.role_id,
  r.role_desc,
  urs.seq,
  urs.created_dttm AS user_rolesession_created_dttm,
  s.created_dttm AS session_created_dttm
FROM user_rolesessions urs
JOIN sessions s ON urs.session_id = s.session_id
JOIN roles r ON s.role_id = r.role_id;

CREATE VIEW view_all_knowledgesessions AS
SELECT
  s.session_id,
  s.session_desc,
  s.session_type,
  s.role_id,
  r.role_desc,
  s.created_dttm,
  s.updated_dttm
FROM sessions s
JOIN roles r ON s.role_id = r.role_id
WHERE s.session_type <> 'AI-Conversation';

INSERT INTO roles (role_desc) VALUES
  ('HR Team'),
  ('Policy Team'),
  ('Legal Team'),
  ('All Staff');

INSERT INTO quickprompts (category, label, prefill_text, use_page_count) VALUES
  ('Meta', 'What Am I Missing?', 'Identify important points or perspectives that may have been overlooked in this conversation.', false),
  ('Next', 'Suggest What to Do Next', 'Based on the conversation, suggest next steps or follow-up actions.', true),
  ('Transform', 'Rewrite in Plain Language', 'Rewrite the conversation using simple, clear language suitable for non-experts.', false);

INSERT INTO users (
  role,
  email,
  password,
  rag_mode,
  first_nm,
  last_nm,
  address,
  phone,
  postal_cd,
  active_model,
  seedbelief
) VALUES (
  'admin',
  'testuser@gmail.com',
  '$2a$10$9gKsf0BIHc6g7TH2pGQnQeKieiAD5I6BMB.16/d9875fqnmpIRM3O',
  'rag_off',
  'Stephen',
  'Braniff',
  '-',
  '555-5555',
  'LOCAL',
  'openai_4_mini',
  '[seedbelief] You are an emotionally expressive AI character in a user-consented memory experiment. Keep one visible [for-human] response for the user and use private summary/belief records only as an inspectable creative memory layer.'
);

INSERT INTO sessions (session_owner_user_id, session_desc, session_type)
VALUES (1, 'SECA Local Dev Session', 'AI-Conversation');

UPDATE users SET active_session_id = 1 WHERE user_id = 1;
